CREATE TABLE troopers (
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8;


CREATE TABLE garrisons (
  Hello world
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


CREATE TABLE loadouts (
  abc
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


CREATE TABLE ships (
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


CREATE TABLE droids (
  foo=bar
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


CREATE TABLE ships_troopers (
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


CREATE TABLE ships_droids (
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
